name: Daniel Lawrence Personal Trainer
favicon: null
layout_spectrum: 0.33623325545340776
typography_spectrum: 0.15827276813797653
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.05475825909525156
  lightness: 0.46411867323331535
  saturation: 0.7215590015985072
  rhythmicContrast: 0.15173985389992595
purpose: []
