name: Daniel Lawrence Personal Trainer
favicon: null
layout_spectrum: 0.5910393458325416
typography_spectrum: 0.041934313252568245
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.372748582623899
  lightness: 0.12076161941513419
  saturation: 0.7158988330047578
  rhythmicContrast: 0.6123602415900677
purpose: []
