name: Daniel Lawrence Personal Trainer
favicon: null
layout_spectrum: 0.6991920017171651
typography_spectrum: 0.3992080185562372
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.7845885204151273
  lightness: 0.676160033326596
  saturation: 0.46131647657603025
  rhythmicContrast: 0.5912331957370043
purpose: []
