name: Daniel Lawrence Personal Trainer
favicon: null
layout_spectrum: 0.5178823419846594
typography_spectrum: 0.1911373462062329
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.6919756142888218
  lightness: 0.43617599993012846
  saturation: 0.3727615256793797
  rhythmicContrast: 0.5095166985411197
purpose: []
