name: Daniel Lawrence Personal Trainer
favicon: null
layout_spectrum: 0.997881043003872
typography_spectrum: 0.29114222060889006
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.237349919276312
  lightness: 0.9073903243988752
  saturation: 0.6053914709482342
  rhythmicContrast: 0.31052698963321745
purpose: []
