name: Daniel Lawrence Personal Trainer
favicon: null
layout_spectrum: 0.47507381974719465
typography_spectrum: 0.9671181456651539
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.26705837855115533
  lightness: 0.9658986672293395
  saturation: 0.9031432708725333
  rhythmicContrast: 0.2954948910046369
purpose: []
