name: Daniel Lawrence Personal Trainer
favicon: null
layout_spectrum: 0.006290421821177006
typography_spectrum: 0.025264485040679574
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.45523374364711344
  lightness: 0.4378560124896467
  saturation: 0.977375925751403
  rhythmicContrast: 0.6263032520655543
purpose: []
