name: Daniel Lawrence Personal Trainer
favicon: null
layout_spectrum: 0.8847711151465774
typography_spectrum: 0.5672298378776759
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.9657627753913403
  lightness: 0.477426465600729
  saturation: 0.10997495311312377
  rhythmicContrast: 0.6166379253845662
purpose: []
