name: Daniel Lawrence Personal Trainer
favicon: null
layout_spectrum: 0.27915184618905187
typography_spectrum: 0.9041369284968823
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.22756699030287564
  lightness: 0.35221532569266856
  saturation: 0.8756226690020412
  rhythmicContrast: 0.12614653422497213
purpose: []
