name: Daniel Lawrence Personal Trainer
favicon: null
layout_spectrum: 0.7757179432082921
typography_spectrum: 0.6026725918054581
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.643159591825679
  lightness: 0.5934215113520622
  saturation: 0.6389562683179975
  rhythmicContrast: 0.6354599974583834
purpose: []
