name: Daniel Lawrence Personal Trainer
favicon: null
layout_spectrum: 0.7883716924116015
typography_spectrum: 0.9687583455815911
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.18855420709587634
  lightness: 0.6964670598972589
  saturation: 0.40967120905406773
  rhythmicContrast: 0.056991351302713156
purpose: []
