name: Daniel Lawrence Personal Trainer
favicon: null
layout_spectrum: 0.21119
typography_spectrum: 0.51354
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.5
  lightness: 0.7025177753530443
  saturation: 0.25
  rhythmicContrast: 0.3011805310379714
purpose: []
